# Generated by Django 3.2.19 on 2023-07-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0019_auto_20220921_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='lecture_name',
        ),
    ]
