# Generated by Django 3.2.19 on 2023-09-03 15:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0020_remove_classname_lecture_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Kost : ')),
                ('spec', ckeditor.fields.RichTextField(verbose_name='Spesifikasi Kost')),
                ('link', models.CharField(max_length=255, verbose_name='Link Google Maps : ')),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='classname',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Peleton : '),
        ),
    ]
